name = "cf-mail"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "cf_mail_db"
database_id = "2757e1fe-e15c-4668-bd05-c02504f6bdb1"

[[r2_buckets]]
binding = "R2"
bucket_name = "cf-mail-storage"

[vars]
ADMIN_PASSWORD = "mycftempemail.pwd"

[assets]
directory = "public"
